# -- Markup --
# These settings are required for the theme to function.

[goldmark]
[goldmark.renderer]
  unsafe = true

[highlight]
  noClasses = false

[tableOfContents]
  startLevel = 2
  endLevel = 4

[math]
  enable = true
  # KaTeX options
  [math.katex]
    # See https://github.com/KaTeX/KaTeX/blob/master/docs/options.md
    displayMode = true
    output = 'html'
    strict = false
    throwOnError = false
    errorColor = '#cc0000'
    trust = true
    macros = {}
