# netlify.toml

[build]
  command = "git submodule update --init --recursive && hugo --gc --minify"
  publish = "public"
  ignore = "echo 'Ignore rule: skipping netlify.toml'"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.16"
  TZ = "UTC"  # Set to preferred timezone

[context.production.environment]
  HUGO_VERSION = "0.104.1"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.104.1"